package dto;
// Generated 03/08/2018 12:14:52 AM by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

    private int clienteId;
    private String apellido;
    private String nombre;
    private Integer cedula;
    private String direccion;
    private Date fechaNacimiento;
    private Boolean activo;

    public String getNombreCompleto() {
        return nombre + " " + apellido;
    }

    public Boolean getActivo() {
        return activo;
    }

    public void setActivo(Boolean activo) {
        this.activo = activo;
    }

    public Cliente() {
    }

    public Cliente(String apellido, String nombre, Integer cedula, String direccion, Date fechaNacimiento) {
        this.apellido = apellido;
        this.nombre = nombre;
        this.cedula = cedula;
        this.direccion = direccion;
        this.fechaNacimiento = fechaNacimiento;
    }

    public int getClienteId() {
        return clienteId;
    }

    public void setClienteId(int clienteId) {
        this.clienteId = clienteId;
    }

    public String getApellido() {
        return this.apellido;
    }

    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Integer getCedula() {
        return this.cedula;
    }

    public void setCedula(Integer cedula) {
        this.cedula = cedula;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }

    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }

    @Override
    public String toString() {
        return "Cliente{" + "apellido=" + apellido + ", nombre=" + nombre + ", cedula=" + cedula + '}';
    }

    @Override
    public int hashCode() {
        int hash = 3;
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Cliente other = (Cliente) obj;
        if (this.clienteId != other.clienteId) {
            return false;
        }
        return true;
    }

}
