/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fomerca.view;

import javax.swing.ImageIcon;
import javax.swing.JLabel;
import util.Constantes;
import util.SessionSettings;

/**
 *
 * @author Adonis
 */
public class VentanaMenu extends javax.swing.JFrame {

    /**
     * Creates new form VentanaMenu
     */
    public VentanaMenu() {
        initComponents();
        setLocationRelativeTo(null);

        JLabel label = new JLabel();
        label.setIcon(new ImageIcon(getClass().getResource("/resource/fomerca_inicio.png")));
        label.setAlignmentX(this.getAlignmentX());
        label.setAlignmentY(this.getAlignmentY());
        label.setSize(this.getSize());
        this.add(label);

        if (SessionSettings.getUser().getPerfil().equals(Constantes.PERFIL_ADMIN)) {
            ButtonRegistry.setVisible(true);
            ButtonInventary.setVisible(true);
        } else {
            ButtonRegistry.setVisible(false);
            ButtonInventary.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonRegistry = new javax.swing.JButton();
        ButtonClientes = new javax.swing.JButton();
        ButtonInventary = new javax.swing.JButton();
        ButtonVentas = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        buttonFacturas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        ButtonRegistry.setBackground(new java.awt.Color(102, 0, 0));
        ButtonRegistry.setForeground(new java.awt.Color(255, 255, 255));
        ButtonRegistry.setText("Registrar");
        ButtonRegistry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistryActionPerformed(evt);
            }
        });

        ButtonClientes.setBackground(new java.awt.Color(102, 0, 0));
        ButtonClientes.setForeground(new java.awt.Color(255, 255, 255));
        ButtonClientes.setText("Clientes");
        ButtonClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonClientesActionPerformed(evt);
            }
        });

        ButtonInventary.setBackground(new java.awt.Color(102, 0, 0));
        ButtonInventary.setForeground(new java.awt.Color(255, 255, 255));
        ButtonInventary.setText("Inventario");
        ButtonInventary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInventaryActionPerformed(evt);
            }
        });

        ButtonVentas.setBackground(new java.awt.Color(102, 0, 0));
        ButtonVentas.setForeground(new java.awt.Color(255, 255, 255));
        ButtonVentas.setText("Ventas");
        ButtonVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVentasActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(102, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Constantes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonFacturas.setBackground(new java.awt.Color(102, 0, 0));
        buttonFacturas.setForeground(new java.awt.Color(255, 255, 255));
        buttonFacturas.setText("Facturas");
        buttonFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacturasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(266, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonRegistry)
                    .addComponent(jButton1)
                    .addComponent(ButtonVentas)
                    .addComponent(ButtonInventary)
                    .addComponent(ButtonClientes)
                    .addComponent(buttonFacturas))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(ButtonVentas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonInventary)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFacturas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonClientes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonRegistry)
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonInventaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInventaryActionPerformed
        VentanaConfiguracionProductos ventanaConfiguracionProductos = new VentanaConfiguracionProductos();
        ventanaConfiguracionProductos.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonInventaryActionPerformed

    private void ButtonRegistryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistryActionPerformed
        VentanaRegistrarUsuario ventanaRegistrarUsuario = new VentanaRegistrarUsuario();
        ventanaRegistrarUsuario.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonRegistryActionPerformed

    private void ButtonClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonClientesActionPerformed
        VentanaConfiguracionCliente ventanaConfiguracionCliente = new VentanaConfiguracionCliente();
        ventanaConfiguracionCliente.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonClientesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        VentanaConfiguracionConstantes ventanaConfiguracionConstantes = new VentanaConfiguracionConstantes();
        ventanaConfiguracionConstantes.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ButtonVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVentasActionPerformed
        VentanaVentas ventanaVentas = new VentanaVentas();
        ventanaVentas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonVentasActionPerformed

    private void buttonFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacturasActionPerformed
        VentanaFacturas ventanaFacturas = new VentanaFacturas();
        ventanaFacturas.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonFacturasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonClientes;
    private javax.swing.JButton ButtonInventary;
    private javax.swing.JButton ButtonRegistry;
    private javax.swing.JButton ButtonVentas;
    private javax.swing.JButton buttonFacturas;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
