/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fomerca.view;

import dto.Cliente;
import dto.Factura;
import dto.Producto;
import dto.RelFacturaProducto;
import facade.UserSessionBean;
import facade.local.UserSessionBeanLocal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListSelectionModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import util.JasperUtil;

/**
 *
 * @author Adonis
 */
public class VentanaVentas extends javax.swing.JFrame {

    private UserSessionBeanLocal userSessionBeanLocal = new UserSessionBean();

    private List<Producto> productos;

    private List<Cliente> clientes;

    private Factura factura = new Factura();

    private Cliente clienteSelected;

    private Producto productoSelected;

    private RelFacturaProducto relFacturaProductoSelected;

    private List<RelFacturaProducto> relFacturaProductos = new ArrayList<RelFacturaProducto>();

    public void recargar() {
        productos = userSessionBeanLocal.getProductos(null);
        clientes = userSessionBeanLocal.getClientes(null);
        listFieldClientes.setListData(userSessionBeanLocal.listaLabelsClientes(null));
        listFieldProductos.setListData(userSessionBeanLocal.listaLabelsProductos(null));
        factura = new Factura(new Date(), clienteSelected);
        relFacturaProductos.clear();
        listFieldProductosSeleccionados.setListData(
                userSessionBeanLocal.listaLabelsRelFacturaProducto(relFacturaProductos));
    }

    /**
     * Creates new form VentanaVentas
     */
    public VentanaVentas() {
        initComponents();
        setLocationRelativeTo(null);
        JLabel label = new JLabel();
        label.setIcon(new ImageIcon(getClass().getResource("/resource/fondo_constante.jpg")));
        label.setAlignmentX(this.getAlignmentX());
        label.setAlignmentY(this.getAlignmentY());
        label.setSize(this.getSize());
        this.add(label);

        productos = userSessionBeanLocal.getProductos(null);
        clientes = userSessionBeanLocal.getClientes(null);
        listFieldClientes.setListData(userSessionBeanLocal.listaLabelsClientes(null));
        listFieldProductos.setListData(userSessionBeanLocal.listaLabelsProductos(null));

        listFieldClientes.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        listFieldClientes.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int index = listFieldClientes.getSelectedIndex();
                if (index >= 0) {
                    clienteSelected = clientes.get(index);
                    labelCliente.setText(clienteSelected.toString());
                } else {
                    clearCliente();
                }
            }
        });
        listFieldProductos.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        listFieldProductos.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int index = listFieldProductos.getSelectedIndex();
                if (index >= 0) {
                    productoSelected = productos.get(listFieldProductos.getSelectedIndex());
                } else {
                    clearProducto();
                }
            }
        });
        listFieldProductosSeleccionados.setSelectionMode(DefaultListSelectionModel.SINGLE_SELECTION);
        listFieldProductosSeleccionados.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int index = listFieldProductosSeleccionados.getSelectedIndex();
                if (index >= 0) {
                    relFacturaProductoSelected
                            = relFacturaProductos.get(
                                    listFieldProductosSeleccionados.getSelectedIndex());
                } else {
                    relFacturaProductoSelected = null;
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldProductoDescripcion = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listFieldProductos = new javax.swing.JList<>();
        textFieldCliente = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listFieldClientes = new javax.swing.JList<>();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        labelCliente = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listFieldProductosSeleccionados = new javax.swing.JList<>();
        buttonAgregarNuevoCliente = new javax.swing.JButton();
        buttonAgregarProducto = new javax.swing.JButton();
        buttonAgregarNuevoProducto = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        buttonVolver = new javax.swing.JButton();
        labelTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Ventas");

        textFieldProductoDescripcion.setToolTipText("Busca productos por su descripcion");
        textFieldProductoDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldProductoDescripcionKeyTyped(evt);
            }
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldProductoDescripcionKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldProductoDescripcionKeyReleased(evt);
            }
        });

        listFieldProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listFieldProductos);

        textFieldCliente.setToolTipText("Busca clientes por su nombre.");
        textFieldCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldClienteActionPerformed(evt);
            }
        });
        textFieldCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                textFieldClienteKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldClienteKeyReleased(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Productos");

        listFieldClientes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listFieldClientes);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cliente:");

        labelCliente.setForeground(new java.awt.Color(255, 255, 255));
        labelCliente.setText("jLabel5");

        listFieldProductosSeleccionados.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listFieldProductosSeleccionados);

        buttonAgregarNuevoCliente.setBackground(new java.awt.Color(102, 0, 0));
        buttonAgregarNuevoCliente.setForeground(new java.awt.Color(255, 255, 255));
        buttonAgregarNuevoCliente.setText("Agregar Cliente Nuevo");
        buttonAgregarNuevoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarNuevoClienteActionPerformed(evt);
            }
        });

        buttonAgregarProducto.setBackground(new java.awt.Color(102, 0, 0));
        buttonAgregarProducto.setForeground(new java.awt.Color(255, 255, 255));
        buttonAgregarProducto.setText("Agregar");
        buttonAgregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarProductoActionPerformed(evt);
            }
        });

        buttonAgregarNuevoProducto.setBackground(new java.awt.Color(102, 0, 0));
        buttonAgregarNuevoProducto.setForeground(new java.awt.Color(255, 255, 255));
        buttonAgregarNuevoProducto.setText("Agregar Producto Nuevo");
        buttonAgregarNuevoProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAgregarNuevoProductoActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(102, 0, 0));
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Quitar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(102, 0, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Finalizar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        buttonVolver.setBackground(new java.awt.Color(102, 0, 0));
        buttonVolver.setForeground(new java.awt.Color(255, 255, 255));
        buttonVolver.setText("Volver");
        buttonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonVolverActionPerformed(evt);
            }
        });

        labelTotal.setForeground(new java.awt.Color(255, 255, 255));
        labelTotal.setText("jLabel5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane3)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonVolver)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton6))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFieldCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonAgregarProducto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonAgregarNuevoProducto))
                            .addComponent(jLabel3)
                            .addComponent(textFieldProductoDescripcion)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonAgregarNuevoCliente)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldProductoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAgregarNuevoCliente)
                    .addComponent(buttonAgregarProducto)
                    .addComponent(buttonAgregarNuevoProducto))
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(labelTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(buttonVolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldClienteActionPerformed

    private void buttonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonVolverActionPerformed
        VentanaMenu ventanaMenu = new VentanaMenu();
        ventanaMenu.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_buttonVolverActionPerformed

    private void textFieldProductoDescripcionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldProductoDescripcionKeyTyped
    }//GEN-LAST:event_textFieldProductoDescripcionKeyTyped

    private void textFieldClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldClienteKeyTyped
    }//GEN-LAST:event_textFieldClienteKeyTyped

    private void textFieldProductoDescripcionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldProductoDescripcionKeyPressed
    }//GEN-LAST:event_textFieldProductoDescripcionKeyPressed

    private void textFieldProductoDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldProductoDescripcionKeyReleased
        if (textFieldProductoDescripcion.getText() != null) {
            clearProducto();
            listFieldProductos.setListData(
                    userSessionBeanLocal.listaLabelsProductos(
                            textFieldProductoDescripcion.getText()));
            productos = userSessionBeanLocal.getProductos(textFieldProductoDescripcion.getText());
        }
    }//GEN-LAST:event_textFieldProductoDescripcionKeyReleased

    private void textFieldClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldClienteKeyReleased
        if (textFieldCliente.getText() != null) {
            clearCliente();
            listFieldClientes.setListData(
                    userSessionBeanLocal.listaLabelsClientes(
                            textFieldCliente.getText()));
            clientes = userSessionBeanLocal.getClientes(textFieldCliente.getText());
        }
    }//GEN-LAST:event_textFieldClienteKeyReleased

    private void buttonAgregarNuevoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarNuevoClienteActionPerformed
        VentanaConfiguracionCliente ventanaConfiguracionCliente = new VentanaConfiguracionCliente();
        ventanaConfiguracionCliente.setIsFactura(true);
        ventanaConfiguracionCliente.setVentanaVentas(this);
        ventanaConfiguracionCliente.setVisible(true);
    }//GEN-LAST:event_buttonAgregarNuevoClienteActionPerformed

    private void buttonAgregarNuevoProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarNuevoProductoActionPerformed
        VentanaConfiguracionProductos ventanaConfiguracionProductos
                = new VentanaConfiguracionProductos();
        ventanaConfiguracionProductos.setIsFactura(true);
        ventanaConfiguracionProductos.setVentanaVentas(this);
        ventanaConfiguracionProductos.setVisible(true);
    }//GEN-LAST:event_buttonAgregarNuevoProductoActionPerformed

    private void buttonAgregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAgregarProductoActionPerformed
        if (productoSelected != null) {
            if (userSessionBeanLocal.cantidadProducto(relFacturaProductos, productoSelected) > 0) {
                relFacturaProductos.add(new RelFacturaProducto(factura, productoSelected));
                listFieldProductosSeleccionados.setListData(
                        userSessionBeanLocal.listaLabelsRelFacturaProducto(relFacturaProductos));
                labelTotal.setText(userSessionBeanLocal.total(relFacturaProductos));
            } else {
                JOptionPane.showMessageDialog(null, "No hay mas de este producto disponible.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un producto.");
        }
    }//GEN-LAST:event_buttonAgregarProductoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (relFacturaProductoSelected != null) {
            relFacturaProductos.remove(relFacturaProductoSelected);
            listFieldProductosSeleccionados.setListData(
                    userSessionBeanLocal.listaLabelsRelFacturaProducto(relFacturaProductos));
            labelTotal.setText(userSessionBeanLocal.total(relFacturaProductos));
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un producto.");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (clienteSelected != null) {
            factura.setCliente(clienteSelected);
            String reporte = userSessionBeanLocal.generarGuardarReporteFactura(factura, relFacturaProductos);
            JOptionPane.showMessageDialog(null, "Su reporte ha sido generado correctamente. \n" + reporte);
            VentanaMenu ventanaMenu = new VentanaMenu();
            ventanaMenu.setVisible(true);
            this.setVisible(false);
//            factura.setRelFacturaProductos(userSessionBeanLocal.llenarRelacion(relFacturaProductos));
//            JasperUtil.generarReposte(userSessionBeanLocal.getFacturaReport(factura));
        } else {
            JOptionPane.showMessageDialog(null, "Seleccione un cliente.");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void clearCliente() {
        clientes.clear();
        clienteSelected = null;
        labelCliente.setText("");
    }

    private void clearProducto() {
        productos.clear();
        productoSelected = null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaVentas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaVentas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAgregarNuevoCliente;
    private javax.swing.JButton buttonAgregarNuevoProducto;
    private javax.swing.JButton buttonAgregarProducto;
    private javax.swing.JButton buttonVolver;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel labelCliente;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JList<String> listFieldClientes;
    private javax.swing.JList<String> listFieldProductos;
    private javax.swing.JList<String> listFieldProductosSeleccionados;
    private javax.swing.JTextField textFieldCliente;
    private javax.swing.JTextField textFieldProductoDescripcion;
    // End of variables declaration//GEN-END:variables
}
